name: llvmlite_win-64_wheel_builder

on:
  push:
  workflow_dispatch:

# Add concurrency control
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  VALIDATION_PYTHON_VERSION: "3.12"

jobs:
  win-64-build:
    name: win-64-build
    runs-on: windows-2022
    defaults:
      run:
        shell: bash -elx {0}
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14", "3.15"]
      fail-fast: true

    steps:
      - name: Clone repository
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          force-url: "https://github.com/misaka00251/llvm-windows-x64/releases/download/v11.1.0/LLVM-11.1.0-win64.exe"
          version: "11.1.0"

      - name: Set LLVM_DIR
        run: |
          echo "LLVM_DIR=${{ env.LLVM_PATH }}/lib/cmake/llvm" >> $GITHUB_ENV
          echo "CMAKE_PREFIX_PATH=${{ env.LLVM_PATH }}" >> $GITHUB_ENV

      # https://github.com/llvm/llvm-project/issues/111829
      # Using hard-coded paths to exclusively compile for Visual Studio 2019?
      # Master stroke!
      - name: Redirect hard-coded paths
        shell: bash
        working-directory: ${{ env.LLVM_DIR }}
        run: find ./ -type f -exec sed --debug -i 's#/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise#/Program Files/Microsoft Visual Studio/2022/Enterprise#g' {} \;

      - name: Setup Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Prepare dependencies
        run: pip install setuptools==84

      - name: Build wheel
        run: python setup.py bdist_wheel

      - name: Upload llvmlite wheel
        uses: actions/upload-artifact@v7.0.1
        with:
          name: llvmlite-win-64-py${{ matrix.python-version }}
          path: dist/*.whl
          compression-level: 0
          if-no-files-found: error

      - name: Get current datetime
        run: echo "RELEASE_DATETIME=$(date +%Y%m%dT%H%MZ)" >> $GITHUB_ENV
        shell: bash

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.RELEASE_DATETIME }}
          tag_name: ${{ env.RELEASE_DATETIME }}
          files: dist/*.whl